import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { Toaster } from '@/components/ui/sonner';
import "driver.js/dist/driver.css";
import SessionProvider from '@/app/providers/SessionProvider';
import AuthProvider from './providers/AuthProvider';


// Configure the font
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Named Patient Program",
  description: "Generated by NPP",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        {/* <AuthProvider> */}
        <ReactQueryProvider>
          <SessionProvider>

            {children}
            <Toaster position="top-center" />
          </SessionProvider>
        </ReactQueryProvider>
        {/* </AuthProvider> */}
      </body>
      <script
        src="https://accounts.google.com/gsi/client"
        async
        defer
      ></script>

    </html>
  );
}
